### ISSUE TITLE
Actions list retaining previous actions when changing model

### ISSUE THREAD

**Issue by RoseOO** [bitfocus/companion-module-datavideo-dvip#1]
I've made quite a lot of progress on the module but there is one bug I can't seem to figure out. When you have an existing instance and change the model the actions don't reload. Though I have code there to do it and it appears to be working the form on the web interface will still show the old actions and values. I was wondering if you may be able to take a glance and see if I've missed something.

Thanks :)

@josephdadams

**Comment by krocheck** [comment]
That's a standing issue (though I don't think there's an actual issue filed on the topic).

Do the actions show correctly after a Companion restart?

**Comment by RoseOO** [comment]
@krocheck Yes the actions do show correctly after restarting companion. Interestingly the feedback options reload fine.

**Comment by krocheck** [comment]
Correct.  That's because of a structural difference in how those two
systems were programmed ... feedback came later and fixed some things.

*----------------------------------------------*Keith Rocheck

*216.856.1377keith.rocheck@gmail.com <keith.rocheck@gmail.com>*

**Comment by MeestorX** [comment]
Be great to fix this as my module is plagued by this issue as well.

**Comment by JeffreyDavidsz** [comment]
@BB21B could not find your slack name, please push to the repo when your are done with all commits. No need to push after eacht commit
![Screenshot_20200412-091517](https://user-images.githubusercontent.com/40557816/79062937-aef21880-7c9e-11ea-9e6c-6b16bd0b4230.jpg)

**Comment by RoseOO** [comment]
@JeffreyDavidsz Oops sorry! Not on Slack and don't use GitHub much, didn't realise it was all linked up and spamming you. I've done all the pretty much most of the work I wanted to do now so I probably won't be updating quite as much.

While I am at it can anyone suggest a better way I can check the return buffers for multiple byte sequences cleaner currently I am using dozens of buffer.indexOf and I would like to tidy to that.

**Comment by krocheck** [comment]
I'll take a look at that.  In the meantime, the protocol spec talks about being able to connect to port 5009 to request an available control port (5001/2, 5003/4, 5005/6, 5007/8).  Would it be smarter to implement that then having the user manually pick?

**Comment by krocheck** [comment]
The only thing I'm thinking of is a little abstractions:
Before

**Comment by krocheck** [comment]
Let's take a look at a single return block:
```javscript
    pos = buffer.indexOf('6e000200', 0, "hex")
    if (pos > -1) {
        //console.log('KEY 4 to', buffer[pos + 4]);
        this.key4_in_src = buffer[pos + 4];
        this.checkFeedbacks('key4_in');
        element = this.model.key4.find(element => element.id === this.key4_in_src.toString());
        if (element !== undefined) {
            this.setVariable('key4_in', element.label);
        }
    }
```

We can abstract a lot of that block to a reusable function, such as:
```javascript
    processSourceAssignment(fbID, varID, state, choices) {
        this.checkFeedbacks(fbID);
        let element = choices.find(element => element.id === state.toString());
        if (element !== undefined) {
            this.setVariable(varID, element.label);
        }
    }
```
That would leave the original block like so:
```javscript
    pos = buffer.indexOf('6e000200', 0, "hex")
    if (pos > -1) {
        //console.log('KEY 4 to', buffer[pos + 4]);
        this.key4_in_src = buffer[pos + 4];
        this.processSourceAssignment('key4_in', 'key4_in', this.key4_in_src, this.model.key4);
    }
```
I forget if this works in JS, but maybe you can do the pos assignment and check in one pass, like this:
```javscript
    if (pos = buffer.indexOf('6e000200', 0, "hex") > -1) {
        //console.log('KEY 4 to', buffer[pos + 4]);
        this.key4_in_src = buffer[pos + 4];
        this.processSourceAssignment('key4_in', 'key4_in', this.key4_in_src, this.model.key4);
    }
```

**Comment by krocheck** [comment]
Without seeing how this raw data is coming down its hard to comment on if the `indexOf` method is the most efficient.  It probably isn't though.  Typically what I'd do in this situation is try to parse the command (the first 8 characters) using a substring and separately the value then run that through a switch:
```javascript
let cmd = buffer.substring(0,8);
let value = buffer.substring(8,1);
switch (cmd) {
    case '6e000200':
        this.key4_in_src = value;
        this.processSourceAssignment('key4_in', 'key4_in', this.key4_in_src, this.model.key4);
        break;
}
```
This is an oversimplification, but if you can parse the data you need out with a little extra work on the front-end that would save you the need for the constant `indexOf` checks later on

**Comment by RoseOO** [comment]
@krocheck Thanks for taking a look, yes I have considered implementing the port negotiation, I've looked at it in Wireshark and it is ever so simple.

I'll look into implementing your suggestions but that does seem a lot clearer. The only thing is, is that there are some common control codes between models for the same function and some that are different but for the same function and some share control codes for completely different functions. S
o I currently have a lot of if statements to delegate between them, so it would be trying to avoid repetition when implementing that. I'll certainly add the processSourceAssignment function though. 

The data coming down the line is pretty much a repeat of what is sent, (with a few exceptions like the initial connection which sends everything in one packet) this is so all the clients can update their state

**Comment by krocheck** [comment]
If you have a `cmd` that is common between two models but handles a different function, I'd probably handle that as an `if-else` within the case.  Likewise if you want a `cmd` to only process for a specific model that would be an `if` within the case as well.

In general with a `switch-case` it shouldn't be a concern for the latter because you'd simply assume that return won't be present and it'll just keep going down the line.  Its only the conflicts you'd need detection inline to handle.

Likewise, assuming there aren't conflicts the other way, you can stack cases:
```javascript
switch (cmd) {
    case '94000200': //se3200
    case '56000200':
        this.pgm_in_src = value;
        this.processSourceAssignment('pgm_in', 'pgm_in', this.pgm_in_src, this.model.pgm);
        break;
}
```

**Comment by RoseOO** [comment]
@krocheck That makes perfect sense thank you.

In case you were interested I've uploaded a small packet capture showing the software startup a few Program and Preview bus changes, a few cuts and. a few autos and the program being closed.

This is on the SE-1200MU so the commands will match with that.

[se-1200mu cap.pcapng.zip](https://github.com/bitfocus/companion-module-datavideo-dvip/files/4466661/se-1200mu.cap.pcapng.zip)

**Comment by RoseOO** [comment]
Just to note I normally filter these packets to see the interesting stuff

 !(data.data == 08:00:00:00:00:00:00:00)&& !(data.data == 08:00:00:00:01:00:00:00) && tcp and not tcp.len==0

**Comment by RoseOO** [comment]
@krocheck Just thinking but because the initial communication packet when you connect contains multiple command command value bytes and currently I can them to read them all but switching on just one position in the buffer wouldn't work.
Do you think a good way would be to loop through each DWORD in the buffer and make the comparisons, if that makes sense?
